name: ci
on:
  push:
    branches:
    - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 8
        format: 'mm.ss'
    - name: Usage
      env:
        TIME: "${{ steps.time.outputs.time }}"
      run: |
        echo $TIME
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ steps.time.outputs.time }}



    - name: update Image Version in the related HelmChart values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        branch: master
        valueFile: 'meu-chart/values.yaml'
        propertyPath: 'image.tag'
        value: ${{ steps.time.outputs.time }}
        commitChange: true
        updateFile: true
        message: "deploy .."
